### PR TITLE
Fix searching for multiple tags

### LINKED ISSUE #84: Search criteria/arguments on Ticket
TAG Version: 2.5.0
GLPI Version: 9.4.4
---
When i try to search in tickets with arguments:

> - Tag containing 'Estorno'
> AND
> - Tag containing 'Doc'
> AND
> - Assigned to Group is 'Suporte'

No results are found.
tags-with-crteria-Suporte

If remove the 'assinged' criteria and keep only Plugin Tag, works fine:
tags-without-criteria-Suporte

### LINKED ISSUE #103: Negative searches when there are several tags
Just upgraded from GLPI 9.4.5 + Tag 2.5.0 to GLPI 9.4.6 + Tag 2.6.0. Searches behaviour on tags changed in a way that's breaking my workflow. I attach tags to tickets and search (for example) with : 

NOT - Plugins - Tag - contains Développement
AND NOT - Plugins - Tag - contains Devis

This used to display every tickets except those with one of the "Développement" or "Devis" tag.
Since the update, it's not filtering correctly anymore. In fact, it will filters tickets which **only** has "Développement" or "Devis" tags. If a ticket has several tags attached (for example, it has "Développement", but also "Sécurité"), it will be displayed. Using the new search criteria, like : 

AND NOT - Plugins - Tag - is - Développement

Or changing the negative entry like

AND - Plugins - Tag - is not - Développement

Has the same result. It's not possible to use negative tags criteria anymore

### PR DESCRIPTION
**Pull request by cconard96**
Fixes #103 
Fixes #84 

Tested multiple search queries to ensure it was fixed.

Screenshot from 2020-07-11 18-04-00
Screenshot from 2020-07-11 18-03-41
Screenshot from 2020-07-11 18-03-13
Screenshot from 2020-07-11 18-02-03

### CODE REVIEW

File: setup.php [hunk 1]
```diff
@@ -26,7 +26,7 @@
  --------------------------------------------------------------------------
  */
 
-define ('PLUGIN_TAG_VERSION', '2.7.0');
+define ('PLUGIN_TAG_VERSION', '2.7.1');
```
Comment (cedric-anne) [inline setup.php:29]: Please do not change it on your PR, it may lead to some conflicts with other PR. We do it when creating release.
```suggestion
define ('PLUGIN_TAG_VERSION', '2.7.0');
```

**Review by cedric-anne — APPROVED** [review]
